services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calendarapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: web-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/calendarapp
      ENABLE_MOCK_SERVER: false
      NEXT_PUBLIC_API_URL: http://localhost:3000/api
      WEATHER_API_BASE_URL: https://api.weatherapi.com/v1/
      WEATHER_APIKEY:

volumes:
  postgres_data:
