name: Build

on:
  push:
    branches:
      - "feature/*"
      - "main"
  pull_request:
    branches:
      - "feature/*" # Ramas que comienzan con 'feature/'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22" # Cambia esto a la versión de Node.js que estés usando

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
